name: Android CI

on:
 repository_dispatch:
#      branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.branch || 'master' }}
        echo: "::set-output name=action_fruit:: ${{ github.event.client_payload.branch || 'master' }}"
    
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
